image: golang
prelude:
- apt-get update
- apt-get install -y git upx
- git clone https://github.com/geaaru/luet
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd luet && git checkout v"${PACKAGE_VERSION}-geaaru" && make build-small && mv luet /usr/bin/luet
includes:
- /usr/bin/luet
