image: "quay.io/mocaccino/extra"
prelude:
- luet install development/make lang/go vcs/git
- mkdir -p go/src/github.com/MottainaiCI/
- cd go/src/github.com/MottainaiCI && git clone https://github.com/MottainaiCI/{{ .Values.name }}.git
# turn the detached message off
- git config --global advice.detachedHead false
env:
- GOPATH=/luetbuild/go/
- GIT_HASH=90bb32c3d19052c2b52a3b6c015b17a42499ece1
- GITHUB_ORG=MottainaiCI
- GITHUB_BRANCH=develop
- LIB_DIR=/var/lib/mottainai
- SRV_DIR=/srv/mottainai
- LUET_YES=true
package_dir: /{{ .Values.name }}
steps:
- cd ${GOPATH}/src/github.com/MottainaiCI/{{ .Values.name }} && git checkout "${GIT_HASH}" && make build
- mkdir -p /{{ .Values.name }}/etc/mottainai
- mkdir -p /{{ .Values.name }}/usr/bin
- mkdir -p /{{ .Values.name }}${LIB_DIR}
- mkdir -p /{{ .Values.name }}${SRV_DIR}/web/artefact
- mkdir -p /{{ .Values.name }}${SRV_DIR}/web/namespace
- mkdir -p /{{ .Values.name }}${SRV_DIR}/web/db
- mkdir -p /{{ .Values.name }}${SRV_DIR}/lock
- |
  cd ${GOPATH}/src/github.com/${GITHUB_ORG}/{{ .Values.name }}/ && \
  mv {{ .Values.name }} /{{ .Values.name }}/usr/bin/{{ .Values.name }} && \
  cp contrib/config/mottainai-server.yaml.example /{{ .Values.name }}/etc/mottainai/mottainai-server.yaml && \
  cp -Rv templates /{{ .Values.name }}${LIB_DIR}/ && \
  cp -Rv public /{{ .Values.name }}${LIB_DIR}
- chmod -R 770 /{{ .Values.name }}${LIB_DIR}
- chmod -R 774 /{{ .Values.name }}${LIB_DIR}/public
- chmod -R 774 /{{ .Values.name }}${SRV_DIR}

