image: "alpine"
package_dir: /{{.Values.name}}

prelude:
- apk add curl

steps:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   YQ_ARCH=amd64 && \
   curl -L https://github.com/mikefarah/yq/releases/download/v${PACKAGE_VERSION}/yq_linux_${YQ_ARCH} -o /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
